# Real Traffic Test — DNS Tunnel Classifier

Tests `dns1.pcapng` and `dns2.pcapng` against the trained model.

**Pipeline:**
1. Load pcapng → packet list (using training extractor)
2. Slide 10-second windows per source IP
3. Extract 38 features per window
4. Predict with `dns_tunnel_classifier.joblib`
5. Analyse results & flag CLI tool issues

In [1]:
import sys, warnings
from pathlib import Path
import numpy as np
import pandas as pd
import joblib

warnings.filterwarnings('ignore')

REPO = Path('.')
PCAP1 = Path(r'C:\Users\acer\Downloads\dns1.pcapng')
PCAP2 = Path(r'C:\Users\acer\Downloads\dns2.pcapng')
MODEL_PATH = REPO / 'dns_tunnel_classifier.joblib'

print('Paths exist?')
for p in [PCAP1, PCAP2, MODEL_PATH]:
    print(f'  {p.name}: {p.exists()} ({p.stat().st_size/1024:.1f} KB)')

Paths exist?
  dns1.pcapng: True (455.1 KB)
  dns2.pcapng: True (69.0 KB)
  dns_tunnel_classifier.joblib: True (1307.9 KB)

## 1. Feature schema audit — CLI tool vs model

In [2]:
# Load model and inspect stored feature list
artifact = joblib.load(MODEL_PATH)

if isinstance(artifact, dict):
    model = artifact['model']
    model_features = artifact.get('features') or artifact.get('feature_names')
else:
    model = artifact
    model_features = list(getattr(model, 'feature_names_in_', []))

print(f'Model type : {type(model).__name__}')
print(f'Stored features ({len(model_features)}): {model_features}')

Model type : VotingClassifier
Stored features (36): ['n_packets', 'duration_sec', 'query_rate', 'unique_qnames', 'unique_subdomains', 'unique_qname_ratio', 'iat_mean', 'iat_std', 'iat_min', 'iat_max', 'payload_mean', 'payload_std', 'payload_max', 'entropy_mean', 'entropy_std', 'subdomain_entropy_mean', 'txt_frac', 'null_frac', 'aaaa_frac', 'a_frac', 'any_frac', 'tunnel_type_frac', 'tcp_frac', 'avg_qname_len', 'avg_subdomain_len', 'avg_label_count', 'avg_max_label_len', 'avg_b64_ratio', 'avg_hex_ratio', 'avg_numeric_ratio', 'avg_consonant_ratio', 'avg_unique_char_ratio', 'n_responses', 'avg_answer_count', 'avg_rdata_len', 'nxdomain_frac']

In [3]:
# CLI tool feature list (from DNS_tunnelling_CLI/feature_extraction.py)
CLI_FEATURES = [
    'n_packets', 'duration_sec', 'query_rate', 'unique_qnames', 'unique_subdomains',
    'unique_qname_ratio', 'iat_mean', 'iat_std', 'iat_min', 'iat_max',
    'payload_mean', 'payload_std', 'payload_max', 'entropy_mean', 'entropy_std',
    'subdomain_entropy_mean', 'txt_frac', 'null_frac', 'aaaa_frac', 'a_frac',
    'any_frac', 'tunnel_type_frac', 'tcp_frac', 'avg_qname_len', 'avg_subdomain_len',
    'avg_label_count', 'avg_max_label_len', 'avg_b64_ratio', 'avg_hex_ratio',
    'avg_numeric_ratio', 'avg_consonant_ratio', 'avg_unique_char_ratio',
    'n_responses', 'avg_answer_count', 'avg_rdata_len', 'nxdomain_frac',
]

model_set = set(model_features)
cli_set   = set(CLI_FEATURES)

missing_in_cli   = model_set - cli_set
extra_in_cli     = cli_set   - model_set

print('=== FEATURE MISMATCH AUDIT ===')
print(f'Model expects  : {len(model_features)} features')
print(f'CLI tool has   : {len(CLI_FEATURES)} features')
print()
print(f'In model but NOT in CLI : {sorted(missing_in_cli) or "none"}')
print(f'In CLI but NOT in model : {sorted(extra_in_cli)   or "none"}')

if missing_in_cli:
    print()
    print('*** CLI tool will CRASH on model load — inference.py raises ValueError ***')
    print('*** Fix: add missing features to EXPECTED_FEATURES and compute_features() ***')

=== FEATURE MISMATCH AUDIT ===
Model expects  : 36 features
CLI tool has   : 36 features

In model but NOT in CLI : none
In CLI but NOT in model : none

## 2. Load pcaps using the TRAINING extractor

We bypass the CLI tool extractor and call `feature_extract.py` directly — it produces the correct feature set.

In [4]:
# Make sure the training extractor is importable
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from feature_extract import (
    pcap_to_packet_list,
    sliding_windows,
    aggregate_window,
)

WINDOW_SEC  = 10.0
STRIDE_SEC  = 10.0   # non-overlapping (matches training)
MIN_PACKETS = 3      # relaxed — real captures may have fewer packets per window

def pcap_to_feature_rows(pcap_path: Path, label_hint: str) -> pd.DataFrame:
    """Read a pcap, slide 10-s windows per source IP, return feature DataFrame."""
    raw = pcap_to_packet_list(str(pcap_path))
    if not raw:
        print(f'  [WARN] No DNS packets found in {pcap_path.name}')
        return pd.DataFrame()

    print(f'{pcap_path.name}: {len(raw)} DNS packets')

    # Summary of IPs and query types
    from collections import Counter
    ips = Counter(p['src_ip'] for p in raw)
    qtypes = Counter(p['qtype'] for p in raw)
    print(f'  Source IPs   : {dict(ips.most_common(5))}')
    print(f'  Query types  : {dict(qtypes.most_common(8))}')
    t_span = max(p['timestamp'] for p in raw) - min(p['timestamp'] for p in raw)
    print(f'  Time span    : {t_span:.1f}s')
    print()

    # Group by source IP, then slide windows
    from collections import defaultdict
    by_ip = defaultdict(list)
    for p in raw:
        by_ip[p['src_ip']].append(p)

    rows = []
    for ip, pkts in by_ip.items():
        pkts.sort(key=lambda p: p['timestamp'])
        for row in sliding_windows(pkts, WINDOW_SEC, STRIDE_SEC, MIN_PACKETS):
            row['src_ip']   = ip
            row['pcap']     = pcap_path.name
            row['hint']     = label_hint
            rows.append(row)

    return pd.DataFrame(rows) if rows else pd.DataFrame()

df1 = pcap_to_feature_rows(PCAP1, label_hint='dns1')
df2 = pcap_to_feature_rows(PCAP2, label_hint='dns2')

df_all = pd.concat([df1, df2], ignore_index=True)
print(f'Total windows extracted: {len(df_all)}')

dns1.pcapng: 1270 DNS packets

  Source IPs   : {'127.0.0.1': 891, '127.0.0.53': 379}

  Query types  : {1: 962, 65: 277, 28: 31}

  Time span    : 384.0s

dns2.pcapng: 46 DNS packets

  Source IPs   : {'127.0.0.1': 26, '127.0.0.53': 20}

  Query types  : {1: 30, 65: 10, 28: 6}

  Time span    : 87.7s

Total windows extracted: 60

## 3. Run inference

In [5]:
FEATURE_COLS = [f for f in model_features if f in df_all.columns]
missing_cols = [f for f in model_features if f not in df_all.columns]

if missing_cols:
    print(f'[WARN] Columns missing from extracted data, filling with 0: {missing_cols}')
    for col in missing_cols:
        df_all[col] = 0.0

X = df_all[model_features].fillna(0).values

# Predict
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    proba  = model.predict_proba(X)

# Determine which column is TUNNEL (class 1)
classes = list(model.classes_)
tunnel_idx = classes.index(1) if 1 in classes else 1
benign_idx = 1 - tunnel_idx

df_all['p_tunnel']  = proba[:, tunnel_idx]
df_all['p_benign']  = proba[:, benign_idx]
df_all['decision']  = (df_all['p_tunnel'] >= 0.5).map({True: 'TUNNEL', False: 'BENIGN'})

# Per-base-learner probabilities
for name, est in model.named_estimators_.items():
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        bp = est.predict_proba(X)[:, tunnel_idx]
    df_all[f'p_tunnel_{name}'] = bp

print('Inference complete.')
print(df_all[['pcap', 'src_ip', 'window_start', 'n_packets', 'decision', 'p_tunnel']].to_string())

Inference complete.

           pcap      src_ip  window_start  n_packets decision  p_tunnel
0   dns1.pcapng   127.0.0.1  1.777906e+09         37   TUNNEL  0.736972
1   dns1.pcapng   127.0.0.1  1.777906e+09         47   BENIGN  0.342352
2   dns1.pcapng   127.0.0.1  1.777906e+09         50   TUNNEL  0.730952
3   dns1.pcapng   127.0.0.1  1.777906e+09         48   TUNNEL  0.865954
4   dns1.pcapng   127.0.0.1  1.777906e+09         46   TUNNEL  0.729563
5   dns1.pcapng   127.0.0.1  1.777906e+09         48   TUNNEL  0.808308
6   dns1.pcapng   127.0.0.1  1.777906e+09         45   TUNNEL  0.860907
7   dns1.pcapng   127.0.0.1  1.777906e+09        197   TUNNEL  0.799255
8   dns1.pcapng   127.0.0.1  1.777906e+09         27   TUNNEL  0.850817
9   dns1.pcapng   127.0.0.1  1.777906e+09         23   TUNNEL  0.671405
10  dns1.pcapng   127.0.0.1  1.777906e+09         53   TUNNEL  0.887994
11  dns1.pcapng   127.0.0.1  1.777906e+09         15   TUNNEL  0.839905
12  dns1.pcapng   127.0.0.1  1.777906e+09         17   TUNNEL  0.811528
13  dns1.pcapng   127.0.0.1  1.777906e+09         60   TUNNEL  0.871404
14  dns1.pcapng   127.0.0.1  1.777906e+09         10   BENIGN  0.130985
15  dns1.pcapng   127.0.0.1  1.777906e+09          4   BENIGN  0.005372
16  dns1.pcapng   127.0.0.1  1.777906e+09          4   BENIGN  0.003363
17  dns1.pcapng   127.0.0.1  1.777906e+09          8   BENIGN  0.097883
18  dns1.pcapng   127.0.0.1  1.777906e+09          6   BENIGN  0.004716
19  dns1.pcapng   127.0.0.1  1.777906e+09          7   BENIGN  0.003363
20  dns1.pcapng   127.0.0.1  1.777906e+09          6   BENIGN  0.005362
21  dns1.pcapng   127.0.0.1  1.777906e+09          8   BENIGN  0.075669
22  dns1.pcapng   127.0.0.1  1.777906e+09          6   BENIGN  0.474405
23  dns1.pcapng   127.0.0.1  1.777906e+09         13   BENIGN  0.221769
24  dns1.pcapng   127.0.0.1  1.777906e+09          8   BENIGN  0.085289
25  dns1.pcapng   127.0.0.1  1.777906e+09         10   BENIGN  0.258243
26  dns1.pcapng   127.0.0.1  1.777906e+09         16   BENIGN  0.041021
27  dns1.pcapng   127.0.0.1  1.777906e+09         12   BENIGN  0.138344
28  dns1.pcapng   127.0.0.1  1.777906e+09         21   TUNNEL  0.841431
29  dns1.pcapng   127.0.0.1  1.777906e+09         28   BENIGN  0.240136
30  dns1.pcapng   127.0.0.1  1.777906e+09          5   BENIGN  0.190715
31  dns1.pcapng   127.0.0.1  1.777906e+09          4   BENIGN  0.006015
32  dns1.pcapng  127.0.0.53  1.777906e+09         38   TUNNEL  0.734717
33  dns1.pcapng  127.0.0.53  1.777906e+09        129   BENIGN  0.335113
34  dns1.pcapng  127.0.0.53  1.777906e+09         40   TUNNEL  0.827071
35  dns1.pcapng  127.0.0.53  1.777906e+09          6   TUNNEL  0.826606
36  dns1.pcapng  127.0.0.53  1.777906e+09         54   TUNNEL  0.860386
37  dns1.pcapng  127.0.0.53  1.777906e+09          7   BENIGN  0.244660
38  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.002705
39  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.004031
40  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.046852
41  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.257698
42  dns1.pcapng  127.0.0.53  1.777906e+09          4   TUNNEL  0.507433
43  dns1.pcapng  127.0.0.53  1.777906e+09          6   BENIGN  0.008962
44  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.056565
45  dns1.pcapng  127.0.0.53  1.777906e+09          4   TUNNEL  0.581214
46  dns1.pcapng  127.0.0.53  1.777906e+09          9   BENIGN  0.175728
47  dns1.pcapng  127.0.0.53  1.777906e+09          8   BENIGN  0.004015
48  dns1.pcapng  127.0.0.53  1.777906e+09          4   BENIGN  0.004682
49  dns1.pcapng  127.0.0.53  1.777906e+09          6   TUNNEL  0.817760
50  dns1.pcapng  127.0.0.53  1.777906e+09          5   BENIGN  0.267301
51  dns1.pcapng  127.0.0.53  1.777906e+09         27   BENIGN  0.210298
52  dns1.pcapng  127.0.0.53  1.777906e+09          3   BENIGN  0.157879
53  dns1.pcapng  127.0.0.53  1.777906e+09          4   BENIGN  0.006015
54  dns2.pcapng   127.0.0.1  1.777907e+09          8   BENIGN  0.046328
55  dns2.pcapng   127.0.0.1  1.777907e+09         12   TUNNEL  0.692147
56  dns2.pcapng   127.0.0.1  1.777907e+09          4   BENIGN  0.047537
57  dns2.pcapng  127.0.0.53  1.777907e+09          5   BENIGN  0.010015
58  dns2.pcapng  127.0.0.53  1.777907e+09         11   BENIGN  0.178486
59  dns2.pcapng  127.0.0.53  1.777907e+09          4   BENIGN  0.033756

## 4. Summary table

In [6]:
base_learner_cols = [c for c in df_all.columns if c.startswith('p_tunnel_')]

summary_cols = ['pcap', 'hint', 'src_ip', 'window_start', 'n_packets',
                'decision', 'p_tunnel'] + base_learner_cols

print('=== CLASSIFICATION RESULTS ===')
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 160)
pd.set_option('display.float_format', '{:.4f}'.format)
display(df_all[summary_cols].sort_values(['pcap', 'src_ip', 'window_start']))

=== CLASSIFICATION RESULTS ===

           pcap  hint      src_ip    window_start  n_packets decision  p_tunnel  p_tunnel_lr  p_tunnel_rf  p_tunnel_gb
0   dns1.pcapng  dns1   127.0.0.1 1777906113.7659         37   TUNNEL    0.7370       0.4578       0.6147       0.9988
1   dns1.pcapng  dns1   127.0.0.1 1777906123.7659         47   BENIGN    0.3424       0.7397       0.4860       0.0001
2   dns1.pcapng  dns1   127.0.0.1 1777906133.7659         50   TUNNEL    0.7310       0.4236       0.6168       0.9988
3   dns1.pcapng  dns1   127.0.0.1 1777906143.7659         48   TUNNEL    0.8660       0.8260       0.7531       0.9988
4   dns1.pcapng  dns1   127.0.0.1 1777906153.7659         46   TUNNEL    0.7296       0.4217       0.6143       0.9988
5   dns1.pcapng  dns1   127.0.0.1 1777906163.7659         48   TUNNEL    0.8083       0.7871       0.6285       0.9988
6   dns1.pcapng  dns1   127.0.0.1 1777906173.7659         45   TUNNEL    0.8609       0.7986       0.7542       0.9988
7   dns1.pcapng  dns1   127.0.0.1 1777906183.7659        197   TUNNEL    0.7993       0.9978       0.5005       0.9988
8   dns1.pcapng  dns1   127.0.0.1 1777906193.7659         27   TUNNEL    0.8508       0.7042       0.7762       0.9988
9   dns1.pcapng  dns1   127.0.0.1 1777906203.7659         23   TUNNEL    0.6714       0.2537       0.5529       0.9988
10  dns1.pcapng  dns1   127.0.0.1 1777906213.7659         53   TUNNEL    0.8880       0.9884       0.7270       0.9988
11  dns1.pcapng  dns1   127.0.0.1 1777906223.7659         15   TUNNEL    0.8399       0.8862       0.6720       0.9847
12  dns1.pcapng  dns1   127.0.0.1 1777906233.7659         17   TUNNEL    0.8115       0.6896       0.6980       0.9860
13  dns1.pcapng  dns1   127.0.0.1 1777906243.7659         60   TUNNEL    0.8714       0.9868       0.6864       0.9987
14  dns1.pcapng  dns1   127.0.0.1 1777906253.7659         10   BENIGN    0.1310       0.3567       0.1491       0.0000
15  dns1.pcapng  dns1   127.0.0.1 1777906273.7659          4   BENIGN    0.0054       0.0000       0.0133       0.0001
16  dns1.pcapng  dns1   127.0.0.1 1777906283.7659          4   BENIGN    0.0034       0.0000       0.0083       0.0001
17  dns1.pcapng  dns1   127.0.0.1 1777906313.7659          8   BENIGN    0.0979       0.0935       0.1979       0.0000
18  dns1.pcapng  dns1   127.0.0.1 1777906333.7659          6   BENIGN    0.0047       0.0001       0.0117       0.0001
19  dns1.pcapng  dns1   127.0.0.1 1777906343.7659          7   BENIGN    0.0034       0.0000       0.0083       0.0001
20  dns1.pcapng  dns1   127.0.0.1 1777906353.7659          6   BENIGN    0.0054       0.0000       0.0133       0.0001
21  dns1.pcapng  dns1   127.0.0.1 1777906373.7659          8   BENIGN    0.0757       0.0208       0.1786       0.0002
22  dns1.pcapng  dns1   127.0.0.1 1777906383.7659          6   BENIGN    0.4744       0.3467       0.4450       0.5677
23  dns1.pcapng  dns1   127.0.0.1 1777906393.7659         13   BENIGN    0.2218       0.2008       0.4539       0.0001
24  dns1.pcapng  dns1   127.0.0.1 1777906403.7659          8   BENIGN    0.0853       0.0743       0.1760       0.0001
25  dns1.pcapng  dns1   127.0.0.1 1777906413.7659         10   BENIGN    0.2582       0.2720       0.5095       0.0001
26  dns1.pcapng  dns1   127.0.0.1 1777906423.7659         16   BENIGN    0.0410       0.0002       0.1024       0.0000
27  dns1.pcapng  dns1   127.0.0.1 1777906433.7659         12   BENIGN    0.1383       0.0107       0.3404       0.0001
28  dns1.pcapng  dns1   127.0.0.1 1777906443.7659         21   TUNNEL    0.8414       0.9471       0.6313       0.9988
29  dns1.pcapng  dns1   127.0.0.1 1777906453.7659         28   BENIGN    0.2401       0.3357       0.4323       0.0002
30  dns1.pcapng  dns1   127.0.0.1 1777906463.7659          5   BENIGN    0.1907       0.0563       0.4485       0.0001
31  dns1.pcapng  dns1   127.0.0.1 1777906493.7659          4   BENIGN    0.0060       0.0000       0.0150       0.0000
32  dns1.pcapng  dns1  127.0.0.53 1777906176.6810         38   TUNNEL    0.7347       1.0000       0.5072       0.8295
33  dns1.pcapng  dns1  127.0.0.53 1777906186.6810        129   BENIGN    0.3351       0.9676       0.3539       0.0001
34  dns1.pcapng  dns1  127.0.0.53 1777906216.6810         40   TUNNEL    0.8271       0.9402       0.6152       0.9823
35  dns1.pcapng  dns1  127.0.0.53 1777906236.6810          6   TUNNEL    0.8266       0.9439       0.6593       0.9353
36  dns1.pcapng  dns1  127.0.0.53 1777906246.6810         54   TUNNEL    0.8604       0.9603       0.6721       0.9987
37  dns1.pcapng  dns1  127.0.0.53 1777906256.6810          7   BENIGN    0.2447       0.6244       0.2994       0.0000
38  dns1.pcapng  dns1  127.0.0.53 1777906276.6810          3   BENIGN    0.0027       0.0000       0.0067       0.0001
39  dns1.pcapng  dns1  127.0.0.53 1777906286.6810          3   BENIGN    0.0040       0.0000       0.0100       0.0001
40  dns1.pcapng  dns1  127.0.0.53 1777906306.6810          3   BENIGN    0.0469       0.0000       0.1171       0.0000
41  dns1.pcapng  dns1  127.0.0.53 1777906316.6810          3   BENIGN    0.2577       0.2844       0.5020       0.0000
42  dns1.pcapng  dns1  127.0.0.53 1777906326.6810          4   TUNNEL    0.5074       0.3964       0.6258       0.4446
43  dns1.pcapng  dns1  127.0.0.53 1777906356.6810          6   BENIGN    0.0090       0.0000       0.0223       0.0001
44  dns1.pcapng  dns1  127.0.0.53 1777906366.6810          3   BENIGN    0.0566       0.0000       0.1414       0.0000
45  dns1.pcapng  dns1  127.0.0.53 1777906376.6810          4   TUNNEL    0.5812       0.9835       0.4677       0.4936
46  dns1.pcapng  dns1  127.0.0.53 1777906396.6810          9   BENIGN    0.1757       0.0428       0.4178       0.0001
47  dns1.pcapng  dns1  127.0.0.53 1777906416.6810          8   BENIGN    0.0040       0.0000       0.0100       0.0000
48  dns1.pcapng  dns1  127.0.0.53 1777906426.6810          4   BENIGN    0.0047       0.0000       0.0117       0.0000
49  dns1.pcapng  dns1  127.0.0.53 1777906436.6810          6   TUNNEL    0.8178       1.0000       0.5584       0.9860
50  dns1.pcapng  dns1  127.0.0.53 1777906446.6810          5   BENIGN    0.2673       0.9269       0.2048       0.0000
51  dns1.pcapng  dns1  127.0.0.53 1777906456.6810         27   BENIGN    0.2103       0.2412       0.4051       0.0000
52  dns1.pcapng  dns1  127.0.0.53 1777906466.6810          3   BENIGN    0.1579       0.0000       0.3946       0.0001
53  dns1.pcapng  dns1  127.0.0.53 1777906496.6810          4   BENIGN    0.0060       0.0000       0.0150       0.0000
54  dns2.pcapng  dns2   127.0.0.1 1777906556.6358          8   BENIGN    0.0463       0.0000       0.1157       0.0001
55  dns2.pcapng  dns2   127.0.0.1 1777906566.6358         12   TUNNEL    0.6921       0.0005       0.7302       1.0000
56  dns2.pcapng  dns2   127.0.0.1 1777906616.6358          4   BENIGN    0.0475       0.0006       0.1185       0.0000
57  dns2.pcapng  dns2  127.0.0.53 1777906556.6361          5   BENIGN    0.0100       0.0000       0.0250       0.0000
58  dns2.pcapng  dns2  127.0.0.53 1777906566.6361         11   BENIGN    0.1785       0.0002       0.4438       0.0024
59  dns2.pcapng  dns2  127.0.0.53 1777906616.6361          4   BENIGN    0.0338       0.0000       0.0843       0.0000

In [7]:
# Per-file verdict summary
print('=== PER-FILE SUMMARY ===')
for pcap_name, grp in df_all.groupby('pcap'):
    n_total  = len(grp)
    n_tunnel = (grp['decision'] == 'TUNNEL').sum()
    n_benign = (grp['decision'] == 'BENIGN').sum()
    avg_p    = grp['p_tunnel'].mean()
    print(f'{pcap_name}:')
    print(f'  Windows : {n_total}  |  TUNNEL: {n_tunnel}  |  BENIGN: {n_benign}')
    print(f'  avg P(tunnel): {avg_p:.4f}')
    print()

=== PER-FILE SUMMARY ===

dns1.pcapng:

  Windows : 54  |  TUNNEL: 21  |  BENIGN: 33

  avg P(tunnel): 0.3809

dns2.pcapng:

  Windows : 6  |  TUNNEL: 1  |  BENIGN: 5

  avg P(tunnel): 0.1680

## 5. Feature-level analysis — what drove each decision?

In [8]:
# Key discriminative features from training analysis
KEY_FEATURES = [
    'query_rate', 'unique_qnames', 'unique_qname_ratio',
    'avg_qname_len', 'avg_subdomain_len', 'avg_max_label_len',
    'entropy_mean', 'subdomain_entropy_mean',
    'avg_b64_ratio', 'avg_hex_ratio', 'avg_unique_char_ratio',
    'tunnel_type_frac', 'txt_frac', 'null_frac',
    'payload_mean', 'payload_max',
    'avg_rdata_len', 'avg_answer_count',
    'base_entropy', 'base_gini',
    'tcp_frac', 'nxdomain_frac',
]

present = [f for f in KEY_FEATURES if f in df_all.columns]

print('=== KEY FEATURE VALUES PER WINDOW ===')
display(df_all[['pcap', 'src_ip', 'decision', 'p_tunnel'] + present]
        .sort_values(['pcap', 'src_ip'])
        .reset_index(drop=True))

=== KEY FEATURE VALUES PER WINDOW ===

,pcap,src_ip,decision,p_tunnel,query_rate,unique_qnames,unique_qname_ratio,avg_qname_len,avg_subdomain_len,avg_max_label_len,...,txt_frac,null_frac,payload_mean,payload_max,avg_rdata_len,avg_answer_count,base_entropy,base_gini,tcp_frac,nxdomain_frac
0,dns1.pcapng,127.0.0.1,TUNNEL,0.7370,4.2691,9,0.2432,23.5135,11.7568,8.6486,...,0.0000,0.0000,46.8649,69.0000,0.0000,0.0000,1.8274,0.6852,0.0000,0.0000
1,dns1.pcapng,127.0.0.1,BENIGN,0.3424,4.7318,12,0.2553,22.1277,9.8511,8.5532,...,0.0000,0.0000,45.9787,69.0000,0.0000,0.0000,2.4736,0.7777,0.0000,0.0000
2,dns1.pcapng,127.0.0.1,TUNNEL,0.7310,5.5809,13,0.2600,24.1200,12.6400,8.8800,...,0.0000,0.0000,50.0400,69.0000,0.0000,0.0000,2.6080,0.8000,0.0000,0.0000
3,dns1.pcapng,127.0.0.1,TUNNEL,0.8660,4.9526,16,0.3333,26.5833,15.3333,9.2917,...,0.0000,0.0000,53.7500,72.0000,0.0000,0.0000,2.3680,0.7457,0.0000,0.0000
4,dns1.pcapng,127.0.0.1,TUNNEL,0.7296,5.3359,16,0.3478,24.6739,14.3913,8.6739,...,0.0000,0.0000,50.3261,72.0000,0.0000,0.0000,2.2390,0.7391,0.0000,0.0000
5,dns1.pcapng,127.0.0.1,TUNNEL,0.8083,4.9822,13,0.2708,24.6667,13.1875,9.2708,...,0.0000,0.0000,50.0000,72.0000,0.0000,0.0000,2.2526,0.7535,0.0000,0.0000
6,dns1.pcapng,127.0.0.1,TUNNEL,0.8609,4.6914,12,0.2667,25.6444,15.2889,9.5556,...,0.0000,0.0000,51.7111,71.0000,0.0000,0.0000,2.2409,0.7477,0.0000,0.0000
7,dns1.pcapng,127.0.0.1,TUNNEL,0.7993,20.3196,20,0.1015,25.0000,13.4721,9.3807,...,0.0000,0.0000,80.0711,106.0000,6.2284,0.7919,2.5594,0.7851,0.0000,0.2893
8,dns1.pcapng,127.0.0.1,TUNNEL,0.8508,2.9351,7,0.2593,27.7037,15.8148,11.3704,...,0.0000,0.0000,51.8148,71.0000,0.0000,0.0000,1.8157,0.6941,0.0000,0.0000
9,dns1.pcapng,127.0.0.1,TUNNEL,0.6714,2.7271,8,0.3478,26.8261,15.4348,11.0870,...,0.0000,0.0000,52.9565,72.0000,0.0000,0.0000,2.1084,0.7372,0.0000,0.0000
10,dns1.pcapng,127.0.0.1,TUNNEL,0.8880,5.6484,8,0.1509,30.5283,20.0000,12.8302,...,0.0000,0.0000,83.3774,105.0000,3.4528,2.3585,1.8655,0.7020,0.0000,0.2830
11,dns1.pcapng,127.0.0.1,TUNNEL,0.8399,1.6664,3,0.2000,22.2000,9.4667,8.5333,...,0.0000,0.0000,43.8667,63.0000,0.0000,0.0000,1.3383,0.5511,0.0000,0.0000
12,dns1.pcapng,127.0.0.1,TUNNEL,0.8115,1.9326,4,0.2353,22.7059,10.1765,8.5882,...,0.0000,0.0000,53.9412,100.0000,3.1765,0.3529,1.4466,0.6021,0.0000,0.0000
13,dns1.pcapng,127.0.0.1,TUNNEL,0.8714,6.7914,6,0.1000,22.7833,10.4167,8.3000,...,0.0000,0.0000,73.5667,100.0000,6.7333,0.4833,0.7245,0.2628,0.0000,0.0833
14,dns1.pcapng,127.0.0.1,BENIGN,0.1310,1.4543,5,0.5000,21.0000,8.0000,8.0000,...,0.0000,0.0000,53.2000,100.0000,0.0000,0.0000,1.3710,0.5600,0.0000,0.0000
15,dns1.pcapng,127.0.0.1,BENIGN,0.0054,0.7056,2,0.5000,16.0000,4.0000,7.5000,...,0.0000,0.0000,39.5000,40.0000,0.0000,0.0000,1.0000,0.5000,0.0000,0.0000
16,dns1.pcapng,127.0.0.1,BENIGN,0.0034,0.9649,2,0.5000,13.5000,2.0000,7.2500,...,0.0000,0.0000,62.0000,100.0000,0.0000,0.0000,0.8113,0.3750,0.0000,0.0000
17,dns1.pcapng,127.0.0.1,BENIGN,0.0979,1.4986,3,0.3750,25.2500,9.5000,10.7500,...,0.0000,0.0000,60.0000,100.0000,4.6250,0.3750,1.5613,0.6562,0.0000,0.0000
18,dns1.pcapng,127.0.0.1,BENIGN,0.0047,0.7313,3,0.5000,18.0000,5.6667,7.6667,...,0.0000,0.0000,39.6667,40.0000,0.0000,0.0000,0.9183,0.4444,0.0000,0.0000
19,dns1.pcapng,127.0.0.1,BENIGN,0.0034,2.1347,2,0.2857,13.0000,2.8571,6.5714,...,0.0000,0.0000,32.5714,41.0000,0.0000,0.0000,0.8631,0.4082,0.0000,0.0000
20,dns1.pcapng,127.0.0.1,BENIGN,0.0054,2.1929,1,0.1667,9.0000,0.0000,6.0000,...,0.0000,0.0000,53.6667,80.0000,4.3333,0.6667,-0.0000,0.0000,0.0000,0.0000
21,dns1.pcapng,127.0.0.1,BENIGN,0.0757,2.3307,3,0.3750,23.7500,9.7500,10.2500,...,0.0000,0.0000,44.5000,52.0000,0.0000,0.0000,1.0000,0.5000,0.0000,0.0000
22,dns1.pcapng,127.0.0.1,BENIGN,0.4744,0.9538,1,0.1667,21.0000,8.0000,8.0000,...,0.0000,0.0000,64.6667,100.0000,4.6667,0.3333,-0.0000,0.0000,0.0000,0.0000
23,dns1.pcapng,127.0.0.1,BENIGN,0.2218,2.4798,4,0.3077,30.8462,15.6154,15.4615,...,0.0000,0.0000,73.5385,105.0000,11.0769,0.9231,1.1401,0.4615,0.0000,0.0000
24,dns1.pcapng,127.0.0.1,BENIGN,0.0853,0.9108,2,0.2500,23.0000,7.5000,10.7500,...,0.0000,0.0000,46.5000,56.0000,0.0000,0.0000,0.8113,0.3750,0.0000,0.0000
25,dns1.pcapng,127.0.0.1,BENIGN,0.2582,1.1096,5,0.5000,24.4000,14.0000,9.6000,...,0.0000,0.0000,51.2000,69.0000,0.0000,0.0000,1.9219,0.7200,0.0000,0.0000
26,dns1.pcapng,127.0.0.1,BENIGN,0.0410,1.8613,4,0.2500,22.4375,9.5625,9.8125,...,0.0000,0.0000,53.6250,100.0000,0.8750,0.1250,1.5052,0.6328,0.0000,0.0625
27,dns1.pcapng,127.0.0.1,BENIGN,0.1383,2.0000,5,0.4167,26.5833,14.4167,10.1667,...,0.0000,0.0000,53.7500,69.0000,0.0000,0.0000,2.2925,0.7917,0.0000,0.0000
28,dns1.pcapng,127.0.0.1,TUNNEL,0.8414,2.2728,7,0.3333,28.4762,16.0476,10.3333,...,0.0000,0.0000,63.5714,106.0000,2.7143,0.3333,2.1991,0.7438,0.0000,0.0952
29,dns1.pcapng,127.0.0.1,BENIGN,0.2401,6.4450,3,0.1071,26.6429,11.2143,11.1429,...,0.0000,0.0000,79.8929,100.0000,6.5714,0.9286,1.0949,0.4388,0.0000,0.0357
30,dns1.pcapng,127.0.0.1,BENIGN,0.1907,0.9279,1,0.2000,29.0000,17.0000,17.0000,...,0.0000,0.0000,62.0000,100.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,0.0000
31,dns1.pcapng,127.0.0.1,BENIGN,0.0060,3.7368,2,0.5000,17.0000,4.0000,8.5000,...,0.0000,0.0000,46.0000,52.0000,0.0000,0.0000,1.0000,0.5000,0.0000,0.0000
32,dns1.pcapng,127.0.0.53,TUNNEL,0.7347,2618.9417,4,0.1053,30.5789,20.8421,8.9737,...,0.0000,0.0000,146.6316,292.0000,6.8158,0.6842,1.2092,0.4806,0.0000,0.6842
33,dns1.pcapng,127.0.0.53,BENIGN,0.3351,18.9558,15,0.1163,23.5969,11.5581,9.4419,...,0.0000,0.0000,97.6434,142.0000,8.2093,1.0930,2.3198,0.7695,0.0000,0.2791
34,dns1.pcapng,127.0.0.53,TUNNEL,0.8271,119.4798,6,0.1500,31.4500,21.1000,13.6500,...,0.0000,0.0000,157.2500,267.0000,5.5000,3.8500,1.5129,0.6350,0.0000,0.4500
35,dns1.pcapng,127.0.0.53,TUNNEL,0.8266,3.5069,2,0.3333,27.0000,14.6667,11.6667,...,0.0000,0.0000,130.3333,136.0000,18.0000,2.0000,0.9183,0.4444,0.0000,0.3333
36,dns1.pcapng,127.0.0.53,TUNNEL,0.8604,5.9517,6,0.1111,21.9815,9.2778,8.1481,...,0.0000,0.0000,86.3704,127.0000,8.9815,0.6296,0.8274,0.2661,0.0000,0.0741
37,dns1.pcapng,127.0.0.53,BENIGN,0.2447,1.8165,4,0.5714,20.2857,7.8571,7.4286,...,0.0000,0.0000,91.0000,121.0000,5.7143,0.4286,0.8631,0.4082,0.0000,0.0000
38,dns1.pcapng,127.0.0.53,BENIGN,0.0027,0.5293,2,0.6667,14.3333,2.6667,7.3333,...,0.0000,0.0000,74.3333,96.0000,17.0000,1.6667,0.9183,0.4444,0.0000,0.0000
39,dns1.pcapng,127.0.0.53,BENIGN,0.0040,0.7237,2,0.6667,14.3333,2.6667,7.3333,...,0.0000,0.0000,89.6667,118.0000,4.0000,0.6667,0.9183,0.4444,0.0000,0.0000
40,dns1.pcapng,127.0.0.53,BENIGN,0.0469,2.6586,2,0.6667,22.6667,8.3333,9.3333,...,0.0000,0.0000,68.0000,80.0000,17.6667,1.0000,0.9183,0.4444,0.0000,0.0000
41,dns1.pcapng,127.0.0.53,BENIGN,0.2577,0.9055,2,0.6667,27.3333,10.3333,12.0000,...,0.0000,0.0000,216.3333,292.0000,24.6667,2.3333,0.9183,0.4444,0.0000,0.0000
42,dns1.pcapng,127.0.0.53,TUNNEL,0.5074,4.6437,2,0.5000,21.5000,8.5000,8.0000,...,0.0000,0.0000,87.0000,119.0000,7.0000,0.5000,-0.0000,0.0000,0.0000,0.0000
43,dns1.pcapng,127.0.0.53,BENIGN,0.0090,10796.1493,1,0.1667,9.0000,0.0000,6.0000,...,0.0000,0.0000,59.0000,80.0000,8.6667,1.0000,-0.0000,0.0000,0.0000,0.0000
44,dns1.pcapng,127.0.0.53,BENIGN,0.0566,35.0922,2,0.6667,25.3333,10.3333,11.6667,...,0.0000,0.0000,134.6667,256.0000,17.6667,5.0000,-0.0000,0.0000,0.0000,0.0000
45,dns1.pcapng,127.0.0.53,TUNNEL,0.5812,6592.2263,1,0.2500,21.0000,8.0000,8.0000,...,0.0000,0.0000,86.5000,118.0000,7.0000,0.5000,-0.0000,0.0000,0.0000,0.0000
46,dns1.pcapng,127.0.0.53,BENIGN,0.1757,5.7832,4,0.4444,29.4444,14.5556,14.3333,...,0.0000,0.0000,168.6667,241.0000,46.0000,1.8889,1.3516,0.5679,0.0000,0.0000
47,dns1.pcapng,127.0.0.53,BENIGN,0.0040,1.9097,3,0.3750,14.8750,4.6250,7.7500,...,0.0000,0.0000,115.8750,226.0000,24.0000,2.5000,1.2988,0.5312,0.0000,0.1250
48,dns1.pcapng,127.0.0.53,BENIGN,0.0047,1.0354,2,0.5000,17.0000,4.0000,8.5000,...,0.0000,0.0000,79.0000,96.0000,19.5000,1.5000,1.0000,0.5000,0.0000,0.0000
49,dns1.pcapng,127.0.0.53,TUNNEL,0.8178,1.0785,2,0.3333,30.3333,22.0000,10.3333,...,0.0000,0.0000,113.8333,133.0000,2.3333,0.3333,0.9183,0.4444,0.0000,0.6667
50,dns1.pcapng,127.0.0.53,BENIGN,0.2673,3.9553,3,0.6000,27.8000,16.8000,8.8000,...,0.0000,0.0000,126.4000,142.0000,16.8000,2.0000,1.5219,0.6400,0.0000,0.4000
51,dns1.pcapng,127.0.0.53,BENIGN,0.2103,21.6641,3,0.1111,27.0741,11.4074,11.4074,...,0.0000,0.0000,98.8889,133.0000,7.7778,1.1111,0.9683,0.3676,0.0000,0.0741
52,dns1.pcapng,127.0.0.53,BENIGN,0.1579,14.6777,1,0.3333,29.0000,17.0000,17.0000,...,0.0000,0.0000,162.6667,186.0000,7.3333,5.3333,-0.0000,0.0000,0.0000,0.0000
53,dns1.pcapng,127.0.0.53,BENIGN,0.0060,4.5550,2,0.5000,17.0000,4.0000,8.5000,...,0.0000,0.0000,79.0000,96.0000,19.5000,1.5000,1.0000,0.5000,0.0000,0.0000
54,dns2.pcapng,127.0.0.1,BENIGN,0.0463,0.9500,3,0.3750,23.5000,9.5000,11.7500,...,0.0000,0.0000,51.1250,59.0000,0.0000,0.0000,0.8113,0.3750,0.0000,0.0000
55,dns2.pcapng,127.0.0.1,TUNNEL,0.6921,2.3979,5,0.4167,27.8333,15.1667,11.5000,...,0.0000,0.0000,61.5833,100.0000,3.2500,4.0000,1.4591,0.6111,0.0000,0.0000
56,dns2.pcapng,127.0.0.1,BENIGN,0.0475,1.6843,2,0.5000,26.5000,9.5000,12.0000,...,0.0000,0.0000,50.0000,52.0000,0.0000,0.0000,1.0000,0.5000,0.0000,0.0000
57,dns2.pcapng,127.0.0.53,BENIGN,0.0100,2.8473,3,0.6000,19.6000,6.2000,9.8000,...,0.0000,0.0000,84.2000,105.0000,15.2000,1.2000,0.9710,0.4800,0.0000,0.0000
58,dns2.pcapng,127.0.0.53,BENIGN,0.1785,5.3843,5,0.4545,26.4545,13.2727,11.1818,...,0.0000,0.0000,172.2727,315.0000,8.5455,6.0909,1.3222,0.5620,0.0000,0.0909
59,dns2.pcapng,127.0.0.53,BENIGN,0.0338,1.5001,2,0.5000,26.5000,9.5000,12.0000,...,0.0000,0.0000,169.5000,292.0000,28.2500,2.2500,1.0000,0.5000,0.0000,0.0000

In [9]:
# Compare tunnel vs benign windows (if both exist)
if df_all['decision'].nunique() == 2:
    print('=== TUNNEL vs BENIGN FEATURE MEANS ===')
    grp = df_all.groupby('decision')[present].mean().T
    grp['delta'] = (grp.get('TUNNEL', 0) - grp.get('BENIGN', 0)).abs()
    display(grp.sort_values('delta', ascending=False).head(20))
else:
    verdict = df_all['decision'].iloc[0]
    print(f'All windows classified as {verdict} — no contrast available.')
    print('Feature means for these windows:')
    display(df_all[present].mean().sort_values(ascending=False).head(15))

=== TUNNEL vs BENIGN FEATURE MEANS ===

decision                 BENIGN   TUNNEL    delta
query_rate             288.4197 428.2878 139.8681
payload_max            118.4474 110.9091   7.5383
payload_mean            82.9078  76.1527   6.7550
avg_subdomain_len        8.6064  14.2264   5.6200
avg_rdata_len            8.6486   3.6903   4.9583
unique_qnames            3.2368   7.7273   4.4904
avg_qname_len           21.6886  25.7774   4.0887
subdomain_entropy_mean   2.2360   2.8869   0.6509
base_entropy             1.0228   1.5654   0.5426
avg_answer_count         1.1030   0.7644   0.3386
entropy_mean             3.5511   3.7233   0.1722
avg_b64_ratio            0.6787   0.8417   0.1630
unique_qname_ratio       0.4115   0.2568   0.1547
avg_max_label_len        9.9088   9.7734   0.1354
base_gini                0.4374   0.5650   0.1277
tunnel_type_frac         0.1352   0.0087   0.1265
avg_unique_char_ratio    0.6146   0.7240   0.1094
nxdomain_frac            0.0281   0.1345   0.1064
avg_hex_ratio            0.2787   0.3039   0.0252
txt_frac                 0.0000   0.0000   0.0000

## 6. Low-confidence windows (model uncertainty)

In [10]:
uncertain = df_all[(df_all['p_tunnel'] > 0.3) & (df_all['p_tunnel'] < 0.7)].copy()

if len(uncertain) == 0:
    print('No uncertain windows (all predictions strongly confident). Good.')
else:
    print(f'{len(uncertain)} uncertain windows (0.3 < P(tunnel) < 0.7):')
    display(uncertain[['pcap', 'src_ip', 'window_start', 'n_packets',
                        'decision', 'p_tunnel'] + present[:10]])

7 uncertain windows (0.3 < P(tunnel) < 0.7):

,pcap,src_ip,window_start,n_packets,decision,p_tunnel,query_rate,unique_qnames,unique_qname_ratio,avg_qname_len,avg_subdomain_len,avg_max_label_len,entropy_mean,subdomain_entropy_mean,avg_b64_ratio,avg_hex_ratio
1,dns1.pcapng,127.0.0.1,1777906123.7659,47,BENIGN,0.3424,4.7318,12,0.2553,22.1277,9.8511,8.5532,3.6588,2.5261,0.8166,0.3015
9,dns1.pcapng,127.0.0.1,1777906203.7659,23,TUNNEL,0.6714,2.7271,8,0.3478,26.8261,15.4348,11.0870,3.7291,2.9197,0.8134,0.2821
22,dns1.pcapng,127.0.0.1,1777906383.7659,6,BENIGN,0.4744,0.9538,1,0.1667,21.0000,8.0000,8.0000,3.6538,2.7500,0.8750,0.3750
33,dns1.pcapng,127.0.0.53,1777906186.6810,129,BENIGN,0.3351,18.9558,15,0.1163,23.5969,11.5581,9.4419,3.6904,2.4626,0.7881,0.2908
42,dns1.pcapng,127.0.0.53,1777906326.6810,4,TUNNEL,0.5074,4.6437,2,0.5000,21.5000,8.5000,8.0000,3.6758,2.8489,0.8819,0.3542
45,dns1.pcapng,127.0.0.53,1777906376.6810,4,TUNNEL,0.5812,6592.2263,1,0.2500,21.0000,8.0000,8.0000,3.6538,2.7500,0.8750,0.3750
55,dns2.pcapng,127.0.0.1,1777906566.6358,12,TUNNEL,0.6921,2.3979,5,0.4167,27.8333,15.1667,11.5000,3.7244,3.0092,0.9259,0.2574

## 7. CLI tool fix — feature mismatch patch

In [11]:
print('=== CLI TOOL FIX REQUIRED ===')
print()
print('File: DNS_tunnelling_CLI/feature_extraction.py')
print()
print('Problem:')
print('  EXPECTED_FEATURES is missing "base_entropy" and "base_gini".')
print('  inference.py raises ValueError on model load because these features')
print('  are in the model joblib but not in EXPECTED_FEATURES.')
print()
print('Fix A — add to EXPECTED_FEATURES (after "tunnel_type_frac"):')
print()
print('  OLD order (after tunnel_type_frac):')
print('    "tcp_frac", "avg_qname_len", ...')
print()
print('  NEW order:')
print('    "base_entropy", "base_gini", "tcp_frac", "avg_qname_len", ...')
print()
print('Fix B — add computation inside compute_features():')
print()
print('  from collections import Counter')
print('  import math')
print()
print('  def _shannon_entropy_counts(counts):')
print('      n = sum(counts.values())')
print('      if not n: return 0.0')
print('      return -sum((c/n)*math.log2(c/n) for c in counts.values() if c)')
print()
print('  def _gini_counts(counts):')
print('      n = sum(counts.values())')
print('      if not n: return 0.0')
print('      return 1.0 - sum((c/n)**2 for c in counts.values())')
print()
print('  # Inside compute_features(), after extracting qnames:')
print('  base_cnt = Counter("."..join(q.split(".")[-2:]) for q in qnames if q)')
print('  features["base_entropy"] = _shannon_entropy_counts(base_cnt)')
print('  features["base_gini"]    = _gini_counts(base_cnt)')

=== CLI TOOL FIX REQUIRED ===

File: DNS_tunnelling_CLI/feature_extraction.py

Problem:

  EXPECTED_FEATURES is missing "base_entropy" and "base_gini".

  inference.py raises ValueError on model load because these features

  are in the model joblib but not in EXPECTED_FEATURES.

Fix A — add to EXPECTED_FEATURES (after "tunnel_type_frac"):

  OLD order (after tunnel_type_frac):

    "tcp_frac", "avg_qname_len", ...

  NEW order:

    "base_entropy", "base_gini", "tcp_frac", "avg_qname_len", ...

Fix B — add computation inside compute_features():

  from collections import Counter

  import math

  def _shannon_entropy_counts(counts):

      n = sum(counts.values())

      if not n: return 0.0

      return -sum((c/n)*math.log2(c/n) for c in counts.values() if c)

  def _gini_counts(counts):

      n = sum(counts.values())

      if not n: return 0.0

      return 1.0 - sum((c/n)**2 for c in counts.values())

  # Inside compute_features(), after extracting qnames:

  base_cnt = Counter("."..join(q.split(".")[-2:]) for q in qnames if q)

  features["base_entropy"] = _shannon_entropy_counts(base_cnt)

  features["base_gini"]    = _gini_counts(base_cnt)

## 8. Analysis summary & recommendations

In [12]:
print('=== FINAL ANALYSIS ===')
print()

for pcap_name, grp in df_all.groupby('pcap'):
    n          = len(grp)
    n_tunnel   = (grp['decision'] == 'TUNNEL').sum()
    avg_p      = grp['p_tunnel'].mean()
    confident  = ((grp['p_tunnel'] > 0.9) | (grp['p_tunnel'] < 0.1)).sum()

    print(f'{pcap_name}')
    print(f'  Decision distribution : {n_tunnel}/{n} TUNNEL, {n-n_tunnel}/{n} BENIGN')
    print(f'  Mean P(tunnel)        : {avg_p:.4f}')
    print(f'  Confident windows     : {confident}/{n} (p>0.9 or p<0.1)')

    avg_qlen = grp['avg_qname_len'].mean() if 'avg_qname_len' in grp else 'N/A'
    avg_ent  = grp['entropy_mean'].mean()  if 'entropy_mean'  in grp else 'N/A'
    avg_b64  = grp['avg_b64_ratio'].mean() if 'avg_b64_ratio' in grp else 'N/A'

    print(f'  avg_qname_len         : {avg_qlen:.2f}' if isinstance(avg_qlen, float) else f'  avg_qname_len: {avg_qlen}')
    print(f'  entropy_mean          : {avg_ent:.4f}'  if isinstance(avg_ent,  float) else f'  entropy_mean: {avg_ent}')
    print(f'  avg_b64_ratio         : {avg_b64:.4f}'  if isinstance(avg_b64,  float) else f'  avg_b64_ratio: {avg_b64}')
    print()

print()
print('ISSUES TO FIX / INVESTIGATE:')
print()
print('1. CLI TOOL BUG (critical)')
print('   feature_extraction.py is missing base_entropy + base_gini.')
print('   CLI tool crashes on model load. Patch required (see Cell 7).')
print()
print('2. LAB-ENVIRONMENT BIAS (expected)')
print('   The model was trained on lab pcaps, so real traffic may show different')
print('   base entropy / gini profiles. If real benign traffic is misclassified,')
print('   threshold tuning (--threshold 0.7) is the first lever to pull.')
print()
print('3. WINDOW SIZE SENSITIVITY')
print('   If your generated traffic has very few packets per 10s window,')
print('   features like query_rate and entropy will be unreliable.')
print('   Check n_packets per window — windows with < 5 packets are unreliable.')
print()
print('4. PCAPNG vs PCAP')
print('   Scapy reads pcapng fine, but some fields (e.g. nanosecond timestamps)')
print('   may differ. If timestamp resolution looks off, normalise to seconds.')

=== FINAL ANALYSIS ===

dns1.pcapng

  Decision distribution : 21/54 TUNNEL, 33/54 BENIGN

  Mean P(tunnel)        : 0.3809

  Confident windows     : 18/54 (p>0.9 or p<0.1)

  avg_qname_len         : 22.98

  entropy_mean          : 3.6154

  avg_b64_ratio         : 0.7296

dns2.pcapng

  Decision distribution : 1/6 TUNNEL, 5/6 BENIGN

  Mean P(tunnel)        : 0.1680

  Confident windows     : 4/6 (p>0.9 or p<0.1)

  avg_qname_len         : 25.06

  entropy_mean          : 3.6037

  avg_b64_ratio         : 0.8176

ISSUES TO FIX / INVESTIGATE:

1. CLI TOOL BUG (critical)

   feature_extraction.py is missing base_entropy + base_gini.

   CLI tool crashes on model load. Patch required (see Cell 7).

2. LAB-ENVIRONMENT BIAS (expected)

   The model was trained on lab pcaps, so real traffic may show different

   base entropy / gini profiles. If real benign traffic is misclassified,

   threshold tuning (--threshold 0.7) is the first lever to pull.

3. WINDOW SIZE SENSITIVITY

   If your generated traffic has very few packets per 10s window,

   features like query_rate and entropy will be unreliable.

   Check n_packets per window — windows with < 5 packets are unreliable.

4. PCAPNG vs PCAP

   Scapy reads pcapng fine, but some fields (e.g. nanosecond timestamps)

   may differ. If timestamp resolution looks off, normalise to seconds.